backend:
  name: github
  repo: reguv760/gatsby-storeytime

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }

  - name: banner
    label: 'Banner Component'
    files:
      - file: 'src/components/banner/index.md'
        label: 'Home Page banner'
        name: 'banner'
        create: true
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'bannerComponent',
            }
          - { label: 'Title', name: 'bannerTitle', widget: 'string' }
          - { label: 'Text', name: 'bannerText', widget: 'string' }

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/about/index.md'
        label: 'About'
        name: 'about'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'about-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
