backend:
  name: github
  repo: reguv760/gatsby-storeytime
  branch: paypal

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/about/index.md'
        label: 'About'
        name: 'about'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'about-page',
            }
          - { label: 'Title', name: 'aboutTitle', widget: 'string' }
          - { label: 'Body', name: 'aboutBody', widget: 'markdown' }

      - file: 'src/pages/videos/index.md'
        label: 'Video List'
        name: 'videoList'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'video-page',
            }
          - label: 'Videos'
            name: 'videos'
            widget: 'list'
          - { label: 'Video Title', name: 'videoTitle', widget: 'string' }
          - { label: 'Youtube Embed URL', name: 'videoLink', widget: 'string' }

      - file: 'src/pages/singers/index.md'
        label: 'Singer List'
        name: 'singerList'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'singer-page',
            }
          - label: 'Singer'
            name: singer
            widget: 'list'
          - { label: 'Name', name: 'name', widget: 'string' }
          - { label: 'Image', name: 'image', widget: 'image' }
          - { label: 'Body', name: 'body', widget: 'markdown' }

      - file: 'src/pages/events/index.md'
        label: 'Events'
        name: 'events'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'event-page',
            }
          - label: 'Event'
            name: 'event'
            widget: 'list'
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - {
              label: 'Event Date',
              name: 'eventdate',
              widget: 'date',
              default: '',
              format: 'MMM Do YY',
            }
          - {
              label: 'Start time',
              name: 'starttime',
              widget: 'datetime',
              default: '',
              format: 'LLL',
            }

      - file: 'src/pages/donate/index.md'
        label: 'Donate'
        name: 'donate'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'donate-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - { label: 'Paypal ID', name: 'paypalID', widget: 'string' }

  - name: 'layout'
    label: 'Page Layout'
    delete: false
    files:
      - file: 'src/pages/index.md'
        label: 'Company Info, Banner, Footer and Contact Components'
        name: 'home'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'index',
            }
          - { label: 'Enable Banner', name: 'bannerEnabled', widget: 'boolean' }
          - { label: 'Title', name: 'bannerTitle', widget: 'string' }
          - { label: 'Text', name: 'bannerText', widget: 'string' }

          - { label: 'Company Name', name: 'companyName', widget: 'string' }
          - { label: 'Company Logo', name: 'companyLogo', widget: 'image' }

          - label: 'Social Media Icons'
            name: 'socialIcons'
            widget: 'list'
            fields:
              - {
                  label: 'Enable Icon',
                  name: 'socialEnabled',
                  widget: 'boolean',
                }
              - { label: 'Link', name: 'socialLink', widget: 'string' }

          - { label: 'Designed By', name: 'designedBy', widget: 'string' }
          - { label: 'Design Link', name: 'designLink', widget: 'string' }

          - { label: 'Contact Phone', name: 'contactPhone', widget: 'string' }
          - { label: 'Contact Email', name: 'contactEmail', widget: 'string' }
          - {
              label: 'Contact Address',
              name: 'contactAddress',
              widget: 'markdown',
            }
